name: mixpanel_flutter_example
description: Demonstrates how to use the mixpanel_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <3.39.0"

dependencies:
  flutter:
    sdk: flutter

  mixpanel_flutter:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
